name: Release BROKEN4 v1.2

on:
  push:
    branches:
      - main   # jalan kalau ada push ke main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write   # biar bisa push tag & bikin release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure & Build
        run: |
          mkdir build
          cd build
          cmake .. -A x64
          cmake --build . --config Release

      - name: Push tag v1.2
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v1.2 -f
          git push origin v1.2 --force

      - name: Create Release v1.2
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.2
          name: Release v1.2
          files: build/Release/BROKEN4.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BROKEN4
          path: build/Release/BROKEN4.exe
