name: Build BROKEN4

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install required packages
      run: |
        choco install mingw -y
        choco install make -y

    - name: Build BROKEN4
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        make

    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/BROKEN4.exe
        body: |
          BROKEN4 - Example C++ Project Build
          ==================================
          
          This release was built automatically using GitHub Actions.
          The binary is intended for educational and demonstration purposes only.

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BROKEN4
        path: build/BROKEN4.exe
