name: Build BROKEN4

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" ..

    - name: Build with Ninja
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BROKEN4
        path: build/Release/BROKEN4.exe

    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/Release/BROKEN4.exe
        body: |
           BROKEN4 Build

          Features:
          - Advanced visual glitch effects
          - Persistence mechanisms
          - Network propagation
          
           For educational and testing purposes only!
