name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release
  ARTIFACT_NAME: broken

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/setup-msvc@v1
      with:
        arch: x64

    - name: Generate Build Files with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Solution
      run: |
        cd build
        cmake --build . --config ${{ env.BUILD_TYPE }} -- /m

    - name: Create Release Directory
      run: |
        mkdir release
        copy build\\${{ env.BUILD_TYPE }}\\broken.exe release\\
        copy *.dll release\\ 2>nul || echo "No DLLs to copy"

    - name: Install Inno Setup (opsional)
      run: |
        choco install innosetup -y

    - name: Create Installer (opsional)
      run: |
        iscc /O"release" /F"broken_Setup" installer_script.iss || echo "No installer script"

    - name: Zip Release Files
      run: |
        cd release
        7z a ../${{ env.ARTIFACT_NAME }}_Windows_${{ matrix.platform }}_${{ github.ref_name }}.zip *.*

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}_Windows_${{ matrix.platform }}_${{ github.ref_name }}
        path: ${{ env.ARTIFACT_NAME }}_Windows_${{ matrix.platform }}_${{ github.ref_name }}.zip

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}_Windows_${{ matrix.platform }}_${{ github.ref_name }}
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated build of Broken
          Version: ${{ github.ref_name }}
          Build date: ${{ github.event.head_commit.timestamp }}

           WARNING: This software is highly destructive and should only be used in controlled environments.
        files: artifacts/*
        draft: false
        prerelease: false
