name: Auto Release BROKEN4

on:
  push:
    branches:
      - main   # jalan setiap ada push ke main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write   # perlu untuk push tag & release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # biar bisa ambil tag

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure & Build
        run: |
          mkdir build
          cd build
          cmake .. -A x64
          cmake --build . --config Release

      - name: Get next version
        id: version
        shell: bash
        run: |
          # ambil tag terakhir atau fallback v1.0.0
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "Last tag: $LAST_TAG"

          # parse major.minor.patch
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # naikkan patch
          PATCH=$((PATCH+1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "New tag: $NEW_TAG"
          echo "version=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Push new t
