name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build executable
      run: |
        cl /EHsc /O2 /Fe:broken.exe BROKEN\\broken.4.cpp

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: broken.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
