
name: Build and Release Broken

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-headers
          nasm

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build broken1.exe
      shell: msys2 {0}
      run: |
        # Paksa environment MINGW64
        export MSYSTEM=MINGW64
        export PATH="/mingw64/bin:$PATH"
        export CPLUS_INCLUDE_PATH="/mingw64/include"
        export LIBRARY_PATH="/mingw64/lib"

        g++ --version

        # Compile ASM jika ada
        if [ -f "BROKEN1/helper.asm" ]; then
          nasm -f win64 BROKEN1/helper.asm -o helper.obj
          OBJFILES="helper.obj"
        else
          OBJFILES=""
        fi

        # Compile & link C++ + ASM
        g++ -O2 -Wall -Wextra -static -o broken1.exe \
            BROKEN1/broken1.cpp $OBJFILES \
            -lwinmm -luser32 -ldwmapi -lgdi32 -lpsapi -lpthread -lshell32 -lcomdlg32 -ladvapi32 \
            -lsetupapi -lvirtdisk -lcrypt32 -lntdll -lgdiplus \
            -mwindows -Wno-cast-function-type -Wno-missing-field-initializers

    - name: Verify build
      run: |
        if (-not (Test-Path "broken1.exe")) {
          echo "::error::Build failed!"
          exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Broken ${{ github.ref_name }}
        body: |
          Build hasil otomatis dari workflow GitHub Actions.
          - File utama: BROKEN1/broken1.cpp
          - Mendukung inline asm atau file .asm eksternal
        files: broken1.exe
        allowUpdates: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
